[2022-11-22 04:59:46,910] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.load_files.extract_geography_info manual__2022-11-22T04:59:28.752525+00:00 [queued]>
[2022-11-22 04:59:46,962] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.load_files.extract_geography_info manual__2022-11-22T04:59:28.752525+00:00 [queued]>
[2022-11-22 04:59:46,963] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:59:46,964] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 04:59:46,966] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:59:47,048] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_files.extract_geography_info> on 2022-11-22 04:59:28.752525+00:00
[2022-11-22 04:59:47,072] {standard_task_runner.py:52} INFO - Started process 340 to run task
[2022-11-22 04:59:47,094] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'load_files.extract_geography_info', 'manual__2022-11-22T04:59:28.752525+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpfg_lht91', '--error-file', '/tmp/tmpjjkx5h1x']
[2022-11-22 04:59:47,098] {standard_task_runner.py:80} INFO - Job 198: Subtask load_files.extract_geography_info
[2022-11-22 04:59:47,436] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.load_files.extract_geography_info manual__2022-11-22T04:59:28.752525+00:00 [running]> on host 8a647070b091
[2022-11-22 04:59:47,782] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=load_files.extract_geography_info
AIRFLOW_CTX_EXECUTION_DATE=2022-11-22T04:59:28.752525+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-22T04:59:28.752525+00:00
[2022-11-22 04:59:47,822] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 04:59:47,983] {python.py:173} INFO - Done. Returned value was: None
[2022-11-22 04:59:48,064] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=load_files.extract_geography_info, execution_date=20221122T045928, start_date=20221122T045946, end_date=20221122T045948
[2022-11-22 04:59:48,152] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 04:59:48,367] {local_task_job.py:273} INFO - 2 downstream tasks scheduled from follow-on schedule check
