[2022-12-11T08:26:50.404+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table manual__2022-12-11T08:26:43.312404+00:00 [queued]>
[2022-12-11T08:26:50.539+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table manual__2022-12-11T08:26:43.312404+00:00 [queued]>
[2022-12-11T08:26:50.541+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T08:26:50.543+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-11T08:26:50.546+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T08:26:50.736+0000] {taskinstance.py:1383} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-12-11 08:26:43.312404+00:00
[2022-12-11T08:26:50.765+0000] {standard_task_runner.py:55} INFO - Started process 413 to run task
[2022-12-11T08:26:50.822+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'manual__2022-12-11T08:26:43.312404+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmphig3v6nq']
[2022-12-11T08:26:50.836+0000] {standard_task_runner.py:83} INFO - Job 105: Subtask checkfiles.check_weather_table
[2022-12-11T08:26:51.271+0000] {task_command.py:376} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table manual__2022-12-11T08:26:43.312404+00:00 [running]> on host 01c108b234e9
[2022-12-11T08:26:51.782+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T08:26:43.312404+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-11T08:26:43.312404+00:00
[2022-12-11T08:26:51.785+0000] {mysql.py:84} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-12-11T08:26:51.849+0000] {base.py:71} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-12-11T08:26:51.977+0000] {sql.py:315} INFO - Running statement: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location)), parameters: None
[2022-12-11T08:26:52.015+0000] {sql.py:324} INFO - Rows affected: 0
[2022-12-11T08:26:52.149+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221211T082643, start_date=20221211T082650, end_date=20221211T082652
[2022-12-11T08:26:52.301+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-12-11T08:26:52.768+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
