[2022-11-22 05:02:33,778] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.load_files.extract_geography_info manual__2022-11-22T05:02:17.023684+00:00 [queued]>
[2022-11-22 05:02:33,823] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.load_files.extract_geography_info manual__2022-11-22T05:02:17.023684+00:00 [queued]>
[2022-11-22 05:02:33,825] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 05:02:33,826] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 05:02:33,827] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 05:02:33,907] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_files.extract_geography_info> on 2022-11-22 05:02:17.023684+00:00
[2022-11-22 05:02:33,924] {standard_task_runner.py:52} INFO - Started process 375 to run task
[2022-11-22 05:02:33,940] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'load_files.extract_geography_info', 'manual__2022-11-22T05:02:17.023684+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp8skjyy_9', '--error-file', '/tmp/tmp807j9m90']
[2022-11-22 05:02:33,946] {standard_task_runner.py:80} INFO - Job 208: Subtask load_files.extract_geography_info
[2022-11-22 05:02:34,490] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.load_files.extract_geography_info manual__2022-11-22T05:02:17.023684+00:00 [running]> on host 8a647070b091
[2022-11-22 05:02:35,043] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=load_files.extract_geography_info
AIRFLOW_CTX_EXECUTION_DATE=2022-11-22T05:02:17.023684+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-22T05:02:17.023684+00:00
[2022-11-22 05:02:35,100] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 05:02:35,246] {python.py:173} INFO - Done. Returned value was: None
[2022-11-22 05:02:35,305] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=load_files.extract_geography_info, execution_date=20221122T050217, start_date=20221122T050233, end_date=20221122T050235
[2022-11-22 05:02:35,399] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 05:02:35,607] {local_task_job.py:273} INFO - 2 downstream tasks scheduled from follow-on schedule check
