[2022-11-22 05:11:55,768] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.load_files.extract_geography_info manual__2022-11-22T05:11:38.435826+00:00 [queued]>
[2022-11-22 05:11:55,810] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.load_files.extract_geography_info manual__2022-11-22T05:11:38.435826+00:00 [queued]>
[2022-11-22 05:11:55,811] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 05:11:55,813] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 05:11:55,814] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 05:11:55,877] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_files.extract_geography_info> on 2022-11-22 05:11:38.435826+00:00
[2022-11-22 05:11:55,893] {standard_task_runner.py:52} INFO - Started process 515 to run task
[2022-11-22 05:11:55,908] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'load_files.extract_geography_info', 'manual__2022-11-22T05:11:38.435826+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpjomelxzq', '--error-file', '/tmp/tmpwcfn_h0z']
[2022-11-22 05:11:55,912] {standard_task_runner.py:80} INFO - Job 248: Subtask load_files.extract_geography_info
[2022-11-22 05:11:56,160] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.load_files.extract_geography_info manual__2022-11-22T05:11:38.435826+00:00 [running]> on host 8a647070b091
[2022-11-22 05:11:56,568] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=load_files.extract_geography_info
AIRFLOW_CTX_EXECUTION_DATE=2022-11-22T05:11:38.435826+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-22T05:11:38.435826+00:00
[2022-11-22 05:11:56,626] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 05:11:56,774] {python.py:173} INFO - Done. Returned value was: None
[2022-11-22 05:11:56,835] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=load_files.extract_geography_info, execution_date=20221122T051138, start_date=20221122T051155, end_date=20221122T051156
[2022-11-22 05:11:56,929] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 05:11:57,196] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
